### ISSUE TITLE
Making current directory path copy friendly in list directory

### ISSUE THREAD

**Issue by kimmenbert** [mkloubert/vscode-deploy-reloaded#10]
It would be great if path to current directory listed on remote server (SFTP) could be copied.

This way we would start of with `/` as dir, browse remote with Deploy Reloaded: List directory, navigate to the correct directory and copy the path.

Even better I guess would be to skip the whole copy / paste action and have a "Set as remote dir" functionality, but that would be the next level 😄

**Comment by mkloubert** [comment]
@kimmenbert 

**I have released new version 0.21.0**, which is now able to copy a remote path to clipboard:

![demo14](https://user-images.githubusercontent.com/4951215/34599871-e1545eb4-f1f4-11e7-9dfb-37ec24bb203f.gif)

Another new feature is: If you start the listening a remote target again, it will start with the last opened one (if possible).

**Comment by kimmenbert** [comment]
Thanks @mkloubert 
The reloaded version is already a great improvement on a great extension.

Coming from Sublime Text, using sublime SFTP. This feels almost like the same workflow now, with a lot of more possibilities built in 👍

**Comment by mkloubert** [comment]
@kimmenbert 

Thanks a lot! :-)
