### ISSUE TITLE
Tiny doc update

### ISSUE THREAD

**Issue by RocketPop** [mkloubert/vscode-deploy-reloaded#11]
### Description

Incorrect syntax in the Readme showing deployOnSave description. The Wiki page is correct.

### Actual behavior
Readme section (under package) contains:
"deployOnSave": true

### Expected behavior
should be
"deployOnSave": [ "My SFTP folder" ]

### Steps to reproduce

n/a

#### Example config

n/a

### Screenshot

n/a

### Your environment

https://github.com/mkloubert/vscode-deploy-reloaded#packages-

### Additional comments

Sorry for the trivial bug report :)

**Comment by mkloubert** [comment]
@RocketPop 

No, any issue is welcome! :-)

I removed the `deployOnSave` completely, because without the [target](https://github.com/mkloubert/vscode-deploy-reloaded#targets-) part, it does not make sense at this point.
