### ISSUE TITLE
Missing zip target options

### ISSUE THREAD

**Issue by Patta** [mkloubert/vscode-deploy-reloaded#12]
Options for zip targets like fileName, target and mappings are missing in current vesion 0.26.0

**Comment by mkloubert** [comment]
@Patta 

Thanks!

**I have released a new version 0.27.0**, that now contains `fileName` setting for custom output filenames.

`target` has been renamed to `dir`.

**Comment by Patta** [comment]
@mkloubert thanks for the fast release. The problem with the replacement of target is, that now the contents in zip contains the workspace folder structure. With target and dir, we can start deploy on a deeper folder.

**Comment by mkloubert** [comment]
@Patta 

No, the [folder mappings](https://github.com/mkloubert/vscode-deploy-reloaded/wiki/folder_mappings) are available for all targets now.

**Comment by Patta** [comment]
@mkloubert thanks!
