### ISSUE TITLE
Options in sidebar context menu

### ISSUE THREAD

**Issue by kimmenbert** [mkloubert/vscode-deploy-reloaded#15]
I guess this is a big one, and I´m not known with the challenges to make something like this in vscode.
This is a screenshot of the Sublime text SFTP context menu
![screen shot on 2018-01-21 at 00_07_56](https://user-images.githubusercontent.com/4253817/35188901-c1278484-fe3f-11e7-91bc-7c54f8edbdf3.png)

The feature I´m missing the most is to upload a complete folder to remote.

**Comment by mkloubert** [comment]
@kimmenbert 

Sorry for the late answer!

**I have released a new version 0.30.0**, which is now able to start a "deploy operation" from context menu of file explorer or editor:

![demo17](https://user-images.githubusercontent.com/4951215/35311888-3a32e852-00b9-11e8-9229-88cb68215e6a.gif)

**Comment by kimmenbert** [comment]
Amazing! Thank you so much!
