### ISSUE TITLE
sftp: Cannot parse privateKey: Unsupported key format

### ISSUE THREAD

**Issue by xmmmmmovo** [mkloubert/vscode-deploy-reloaded#171]
### Description

When I use private key to deploy my code to my remote server, it says that "Cannot parse privateKey". But I always use this key to login my remote server.

#### Example config

```json
{
  "deploy.reloaded": {
    "packages": [
      {
        "name": "os",

        "deployOnSave": true,

        "files": ["**/**"],

        "targets": ["os"]
      }
    ],
    "targets": [
      {
        "type": "sftp",
        "name": "os",

        "dir": "secret",
        "host": "secret",
        "port": secret,

        "user": "xmmmmmovo",
        "privateKey": "/Users/xmmmmmovo/.ssh/gh-pages"
      }
    ]
  }
}

```

#### Screenshot

Error in vscode:

![image](https://user-images.githubusercontent.com/32405482/108342025-473d2000-7215-11eb-884a-5e7702e9aae3.png)

success to ssh my remote server:

![image](https://user-images.githubusercontent.com/32405482/108342228-85d2da80-7215-11eb-9d0b-e9ad2d53cf3d.png)

I usually use sftp to deploy my project, so I think it's not my server configuration's error.

![image](https://user-images.githubusercontent.com/32405482/108342457-caf70c80-7215-11eb-897a-6bc95384443b.png)

### Your environment

- Operating system: MacOS(6723.81.1)
- Visual Studio Code version: 1.54.0-insider
- Extension version: v0.89.0

**Comment by BuchyOne** [comment]
Depending on how you generate your keys. Current OpenSSH behaviour 

So, if you use: 

`ssh-keygen -o`

gives this first line:

-----BEGIN OPENSSH PRIVATE KEY-----

Try PEM option:

`ssh-keygen -m pem -f /path/to/key`

Then you see 

-----BEGIN RSA PRIVATE KEY-----


'It is still possible for ssh-keygen to write the previously-used PEM format private keys using the -m flag'
from: [[https://man.openbsd.org/ssh-keygen#m](https://man.openbsd.org/ssh-keygen#m)]

**Comment by xmmmmmovo** [comment]
> Depending on how you generate your keys. Current OpenSSH behaviour
> 
> So, if you use:
> 
> `ssh-keygen -o`
> 
> gives this first line:
> 
> -----BEGIN OPENSSH PRIVATE KEY-----
> 
> Try PEM option:
> 
> `ssh-keygen -m pem -f /path/to/key`
> 
> Then you see
> 
> -----BEGIN RSA PRIVATE KEY-----
> 
> 'It is still possible for ssh-keygen to write the previously-used PEM format private keys using the -m flag'
> from: [https://man.openbsd.org/ssh-keygen#m]

Thanks to reply my problem!  After appear this problem, I have been search for solution on Google, and finally I solve this probem by using another plugin named `sftp`

P.S. This problem caused by the dependency named `ssh2-sftp-client`(has been proposed in the repository's issue)
