### ISSUE TITLE
None of the menu option works: command 'extension.deploy.reloaded.anyCommand' not found

### ISSUE THREAD

**Issue by ZiyiFeng-SJSU** [mkloubert/vscode-deploy-reloaded#19]
### Description
When bring up the menu by Ctrl+Shift+P, typed deploy and clicked any command that belong to deploy-reload, error message would occur, such as 
`command 'extension.deploy.reloaded.listDirectory' not found`
`command 'extension.deploy.reloaded.showTools' not found`

### Actual behavior

Error messages come out. 

### Expected behavior

Should go into whichever option that was selected

#### Example config

```json
{
  "deploy.reloaded": {
    "packages": [
      {
        "name": "mobile",
        "description": "Package version 2.3.4",
        "exclude": [
          "tests/**",
          ".vscode/**",
          ".vscode",
          "sftp-config.json",
        ],
        "files": [
          "**"
        ],
      }
    ],
    "targets": [
      {
        "type": "sftp",
        "name": "mobile-site3",
        "description": "mobile v3",
        "dir": "/home/zfeng/src/mobile-site2",
        "host": "***********",
        "user": "*****",
        "privateKey": "/**********",
      }
    ]
  }
}
```
### Your environment

- Operating system: Linux 17.10 64 bit
- Visual Studio Code version: 
```
Version 1.19.3
Commit 7c4205b5c6e52a53b81c69d2b2dc8a627abaa0ba
Date 2018-01-25T10:32:23.601Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```
- Extension version: 0.34.1

**Comment by mkloubert** [comment]
@ZiyiFeng-SJSU 

I have checked this, but have no problems to invoke the commands.

Have you tried to uninstall und reinstall it completly?

Do you use [the old extension](https://github.com/mkloubert/vs-deploy)?

**Comment by ZiyiFeng-SJSU** [comment]
Got it! Reinstall the extension fixed it. Thank you for the help!
