### ISSUE TITLE
List Directory always looking for '/' no matter what "dir" is set to in targets in settings.json

### ISSUE THREAD

**Issue by CambridgePark** [mkloubert/vscode-deploy-reloaded#21]
### Description

List Directory always looking for '/' no matter what "dir" is set to in "targets" within the settings.json file.
Appears to always use default.
Note: All other entries work when changed. 

### Actual behavior

 [vscode-deploy-reloaded]::[my_site] Could not list directory '/'

### Expected behavior

Should try to open  "dir": "/test/test1" 

### Steps to reproduce

CTRL+SHIFT+P
Select Deployed Reloaded List Directory
 [vscode-deploy-reloaded]::[my_site] Could not list directory '/'

#### Example config

```json
{
    "deploy.reloaded": {
        // your config
               "type": "sftp",
               "name": "myname",
               "description": "mydescription",
               "host": "myhost",
               "port": 22,
               "user": "myusername", 
               "password": "mypassword",
               "dir": "/test/test1"     -> ignores
    }
}
```

#### Logs

```
// write log messages here, if possible

// maybe one or more log files are available
// in sub folder '.vscode-deploy-reloaded/.logs'
// inside your home directory
```

#### Screenshot

{Please write here, if possible}

### Your environment

- Operating system: Windows 10
- Visual Studio Code version: 1.20.0
- Extension version: 0.39.1

### Additional comments

{Please write here, if there is something more to tell}

**Comment by mkloubert** [comment]
@CambridgePark 

The `dir` setting the real directory on your server ... all operations, like deploy, pull, delete or listen, work relative to it.

**Comment by CambridgePark** [comment]
When I define the real directory on my server Deploy always says it's loading '/'
Does that mean that when it says '/' and dir is set to = /srv/root/  that I am actually seeing '/' = /srv/root/?

**Comment by mkloubert** [comment]
@CambridgePark 

Right!

**Comment by CambridgePark** [comment]
Great! Thanks for the clarification.
