### ISSUE TITLE
[help-needed] privateKey without privateKeyPassphrase

### ISSUE THREAD

**Issue by jimmynash** [mkloubert/vscode-deploy-reloaded#22]
### Description
Trying to list a remote directory using and sftp target using a privateKey but without a privateKeyPassphrase.

When I run the list directory command it says it could not list the directory.
The key was created without a passphrase. I have confirmed that a different key WITH a passphrase does work to list the directory along with a test of just username and password auth.

### Actual behavior
Get a message saying [vscode-deploy-reloaded]::[target_name] Could not list directory '/' ('target_name'):

### Expected behavior

Directory is listed with secondary commands

### Steps to reproduce

Create privateKey without a passphrase.
Specify in target sftp config: example below

#### Example config

```json
{
    "deploy.reloaded": {
        "packages": [
            {
                "name": "MODULES",
                "description": "MODULES",
                "exclude": [
                    ".vscode/**",
                    ".vscode",
                    ".svn/**",
                    ".svn"
                ]
            }
        ],

        "targets": [
            {
                "type": "sftp",
                "name": "target_name",
                "description": "target_name folder",
                "host": "192.168.5.3",
                "user": "username",
                "privateKey": "/Users/username/.ssh/id_rsa",
                "dir": "/remotedir/"
            }
        ]
    }
}
```

#### Logs

```
INFO extension.deploy.reloaded.loadplugins - [08/Feb/2018:15:51:18 +0000] "Loaded 19 plugins:
- app
- azureblob
- batch
- compiler
- dropbox
- each
- ftp
- list
- local
- mail
- map
- prompt
- s3bucket
- script
- sftp
- slack
- switch
- test
- zip
"
```

### Your environment

- Operating system: macOS 10.13.3
- Visual Studio Code version: 1.20.0
- Extension version: 0.39.1

### Additional comments

I'm looking for a replacement for an old sublime sftp that I was using that is broken in macOS High Sierra. This plugin is awesome but I'm just having trouble figuring out how I can create the config without having to save passwords in it, either regular passwords or keyfile passphrases.

Any help is appreciated!

**Comment by jimmynash** [comment]
I suppose at the end of the day it doesn't really matter as long as the key passphrase is different than the user account password.

I'm just going to use a key with a passphrase and move on.

Just wanted to say thanks once more for this awesome plugin!

**Comment by mkloubert** [comment]
@jimmynash 

**I have released a new version 0.40.0**, which logs the error now to the log files inside your home directory.

Can you update to it and post the error here (search for `list.listDirectory` inside the current log file)?

**Comment by mkloubert** [comment]
@jimmynash 

Thanks a lot!

That means that [ssh2-sftp-client](https://www.npmjs.com/package/ssh2-sftp-client) module, I use in the extension, always expects a passphrase for a private key, what makes sense in my opinion.

**Comment by jimmynash** [comment]
I agree. It was a key that I have been using for awhile and generating one with a passphrase works just fine.

I REALLY appreciate your help checking it out, even if the issue I created seemed like it may be dumb on it's face.

Keep up the great work!
