### ISSUE TITLE
[help-needed documentation?] ignore/exclude files

### ISSUE THREAD

**Issue by jimmynash** [mkloubert/vscode-deploy-reloaded#23]
### Description

I'm attempting to ignore some files from deployment, download or upload using sftp.

Looking over the documentation in the examples I see "exclude" being used but cannot find that as a json property listed in the tables. I do see ignore in the documentation tables.

Which is appropriate to use for ignoring/excluding  things?

### Actual behavior

Add ignore/exclude section to packages specifically to exclude old .svn directories from download.
Pulling folder down and subfolders pulls files mentioned in the package ignore/exclude.

### Expected behavior

Adding a ignore/exclude with correct syntax prevents Deploy Reloaded from downloading files matching those rules.

### Steps to reproduce

Add ignore or exclude (unsure which is correct to use) for remote files to exclude.
Use action to list remote directory with SFTP, choose "Pull files with Subfolders"

#### Example config

```json
}
  "deploy.reloaded": {
    "packages": [
        {
            "name": "MODULES",
            "description": "MODULES",
            "deployOnSave": true,
            "files": [
                "**"
            ],
            "ignore": [
                ".vscode/**",
                ".vscode",
                ".svn/**",
                ".svn"
            ],
            "targets": [ "modules" ],
            "exclude": [
                ".vscode/**",
                ".vscode",
                ".svn/**",
                ".svn"
            ]
        }
    ],

    "targets": [
        {
            "type": "sftp",
            "name": "modules",
            "description": "modules folder",
            "host": "ip_address_of_host",
            "user": "username",
            "privateKey": "/path/to/keyfile",
            "privateKeyPassphrase": "passphrase",
            "dir": "/remotedir"
        }
    ]
  }
}
```

### Your environment

- Operating system: macOS 10.13.3
- Visual Studio Code version: 1.20.0
- Extension version: 0.40.0

### Additional comments

It is very possible that I'm using the incorrect syntax in the ignore or exclude. Just not sure what might be wrong there and if I should be using ignore or exclude.

Thanks!

**Comment by mkloubert** [comment]
@jimmynash 

You have to put the `ignore` setting to the root:

```json
{
  "deploy.reloaded": {
    "ignore": [
        ".vscode/**",
        ".vscode",
        ".svn/**",
        ".svn"
    ],

    "packages": [
        // ...
    ],

    // ...
  }
}
```

BTW.: `.vscode` folders are ignored by default.

**Comment by mkloubert** [comment]
@jimmynash 

**Since version 0.41.0, you do not need to ignore `.svn` folders anymore, this is done by default there.**

You can change this behavior, by setting global config property `ignoreSvnFolder` to `(false)` (for git this setting is called `ignoreGitFolder`).

**Comment by jimmynash** [comment]
OK, I tried moving it, here's my new config snippet:

```json
{
{
  "deploy.reloaded": {
    "ignore": [
        ".svn/**",
    ],
    "packages": [
        {
            "name": "MODULES",
            "description": "MODULES",
            "deployOnSave": true,
            "files": [
                "**"
            ],
            "targets": [ "modules" ]
        }
    ],
}
```

but it still tries to download the .svn directories. The remote files are not yet on the local machine so I'm using the list directory and then the pull files and sub folders action.

Based on your last comment I'll try upgrading and see how that goes.

**Comment by jimmynash** [comment]
Bummer. Upgraded to 0.41.0 but it still pulls the .svn folders from the remote host.

Current config looks like this:

```json
{
  "deploy.reloaded": {
    "packages": [
        {
            "name": "MODULES",
            "description": "MODULES",
            "deployOnSave": true,
            "files": [
                "**"
            ],
            "targets": [ "modules" ]
        }
    ],
```

If it is ignoring the .svn folders should those folders even show in the directory list? When I tell deploy to list the directory it does show the .svn folder on the remote.

Is the "Pull Files with subfolders" action maybe not respecting the ignore?

**Comment by mkloubert** [comment]
@jimmynash 

Ah, OK!

`Pull Files with subfolders` is only a tool for simply pulling files ... it is outside the "normal context", what means, that there are no files, which will be ignored.

If you pull, deploy or delete a file inside the editor (via a package or a single file), the extension will use the patterns, you have defined in the `ignore` setting.

**Comment by jimmynash** [comment]
OK, so just to make sure I understand, the "Pull Files with subfolders" action will always pull everything regardless of ignores in the settings correct?

**Comment by mkloubert** [comment]
@jimmynash 

Correct!

e.g. any `Listen directory` operation do not make use of of the `ignore` patterns, only the "local operations", like deploy, pull or delete, do.

**Comment by jimmynash** [comment]
Good to know. As always thanks for the assistance!
