### ISSUE TITLE
How to remove text "Deploy Reloaded: workspace_name"?

### ISSUE THREAD

**Issue by pythoninja** [mkloubert/vscode-deploy-reloaded#24]
### Description

How can I remove this text?

![image](https://user-images.githubusercontent.com/13417093/36142539-7b343ee0-10b9-11e8-8fcc-f5d79fe1d82c.png)

### Your environment

- Operating system: Ubuntu 16.10
- Visual Studio Code version: 1.20
- Extension version: 0.48

**Comment by mkloubert** [comment]
@pythoninja 

**Since version 0.49.0 the button is hidden by default now**, if there are less than 2 workspaces open.

To activate it, you only need to set `alwaysShowWorkspaceSelector` to `(true)` in the [settings](https://github.com/mkloubert/vscode-deploy-reloaded/wiki#settings--).

**Comment by pythoninja** [comment]
@mkloubert 

Thank you for fixing it!
