### ISSUE TITLE
 [help-needed] Button for deploy specific folder

### ISSUE THREAD

**Issue by vystepanenko** [mkloubert/vscode-deploy-reloaded#25]
Hello!
I want to create a button to deploy specific folder from anywhere in project. Is this possible?

I'll try to do the following

#### Example config
```json
{
    "deploy.reloaded": {
        "packages": [
            {
                "name": "Public to test",
                
                "button": {
                    "text": "Deploy to 'test'",
                    "tooltip": "Click here to deploy to the target...",
                    "targets": [ "Test" ]
                }
            }
        ],
        "targets": [
            {
                "type": "sftp",
                "name": "Test",
                "description": "Test server",
                "dir": "/var/www/html/myProject",
                "mappings": {
                    "/public": "/public"
                }
            }          
        ]
       }
} 
```

But it deploy all my project to server instead  one folder
### Your environment

- Operating system: Windows 10
- Visual Studio Code version: 1.20.1
- Extension version: 0.50.0

**Comment by mkloubert** [comment]
@vystepanenko 

You have to specify [glob patterns](https://github.com/isaacs/node-glob) in `files` (and maybe `exclude`) properties of your [package](https://github.com/mkloubert/vscode-deploy-reloaded/wiki#packages-):

```json
{
    "deploy.reloaded": {
        "packages": [
            {
                "name": "Public to test",

                "files": [
                    "js/*.js",
                    "css/*.css",
                    "**/*.html",
                ],

                "exclude": [
                    "**/*.map",
                ],
                
                "button": {
                    "text": "Deploy to 'test'",
                    "tooltip": "Click here to deploy to the target...",
                    "targets": [ "Test" ]
                }
            }
        ],

        "targets": [
            {
                "type": "sftp",
                "name": "Test",
                "description": "Test server",
                "dir": "/var/www/html/myProject"
            }          
        ]
    }
} 
```

[Folder mappings](https://github.com/mkloubert/vscode-deploy-reloaded/wiki/folder_mappings) only make sense if you want to map a local folder to another one:

```json
{
    "deploy.reloaded": {
        // ...

        "targets": [
            {
                "type": "sftp",
                "name": "Test",
                "description": "Test server",
                "dir": "/var/www/html/myProject",

                "mappings": {
                    "/html/**": "/PUBLIC"
                }
            }          
        ]
    }
} 
```

Anything that is part of `/html` inside your workspace, will be deployed to `/var/www/html/myProject/PUBLIC`.

**Comment by vystepanenko** [comment]
thnx. I specified glob patterns in files properties and its work. 
But I have several targets and when I pres button it still asked me to what exactly target i want to deploy

**Comment by mkloubert** [comment]
@vystepanenko 

Oh ... the feature with the defined target, as described in the [wiki](https://github.com/mkloubert/vscode-deploy-reloaded/wiki#buttons-), is not implemented yet ... I will try to implement this in the next hours.

**Comment by mkloubert** [comment]
@vystepanenko

**The feature is available since version 0.51.0.**

As defined in your example config, the button should only deploy to `Test` target now.

**Comment by vystepanenko** [comment]
thnx. it's really fast)

ps. maybe you know when it will be available in VSC?

**Comment by mkloubert** [comment]
@vystepanenko 

The new version is published and available.

Select `Extensions` tab on the left side (`CTRL + Shift + X`) and search for `vscode-deploy-reloaded` and you should see an "upgrade button".

If this does not work, simply reinstall it.

**Comment by vystepanenko** [comment]
Seems it was some issue with my VSC. All works after I restart it
