### ISSUE TITLE
bug: deploy operation: can't stop

### ISSUE THREAD

**Issue by zamkevich** [mkloubert/vscode-deploy-reloaded#26]
### Actual behavior
if I selected a deployment on sftp and canceled it before starting the deployment
The extension is suspended for "canceling the deployment operation ..."

### Expected behavior
it's must stop :-) 

#### Example config

```json


{
  "deploy.reloaded": {
    "targets": [
      {
        "type": "sftp",
        "name": "#some project",
        "description": "some folder",
        "dir": "/some path",
        "host": "123.123.123.123",
        "port": 22,
        "user": "user",
        "privateKey" : "some path/.ssh/id_rsa",
        "checkBeforeDeploy": true
      }
    ]
  }
}

```
#### Logs
no logs.

#### Screenshot
![image](https://user-images.githubusercontent.com/13717428/36352189-e98a67fc-1500-11e8-97bd-dddf2e1afa93.png)

### Your environment

- Operating system: win10
- Visual Studio Code version: 1.20.1
- Extension version: 0.51.0

**Comment by mkloubert** [comment]
@zamkevich 

**Should be fixed since 0.51.1.**

**Comment by zamkevich** [comment]
Yes, now it works.

**Comment by ynamite** [comment]
Still happens on 0.53.1, there's no log I can see ...
