### ISSUE TITLE
ERROR: '553 Could not create file.' using ftp

### ISSUE THREAD

**Issue by jimschmit** [mkloubert/vscode-deploy-reloaded#27]
### Description

Hello, I try to upload files to an ftp server, but I always get this message:
Deploying file 'd:\edutec\projets\script\frontend\js\cms\app.js' to '/htdocs/js/cms (www2.script.lu)' ... [ERROR: '553 Could not create file.']
Using filezilla it works

###My config:
```json
{
				"name": "www2.script.lu",
				"type": "ftp",
				"host": "script.hosting-restena.lu",
				"port": 21,
				"user": "****",
				"password": "******",
				"dir": "/htdocs/",
				"mappings": {
					"frontend/**": "/htdocs/",
					"frontend/.htaccess": "/htdocs/",
				}
			},

**Comment by mkloubert** [comment]
@jimschmit 

Can you try this?:


```json
{
				"name": "www2.script.lu",
				"type": "ftp",
				"host": "script.hosting-restena.lu",
				"port": 21,
				"user": "****",
				"password": "******",
				"dir": "/htdocs/",
				"mappings": {
					"frontend/**": "/"
				}
			},
```

The mapping directories are relative to your FTP folder, you have specified in `dir`.

As in your example, it would map all `frontend` files to `/htdocs/htdocs`.

**Comment by jimschmit** [comment]
Thank you, this one worked. However, if I specify a directory in the mapping, that does not exists on the server, the plugin does not create it. It would be nice if the directory could be created if it doesn't exist.
```json
"mappings": {
					"frontend/**": "/test",
					"frontend/.htaccess": "/test",
				}
```
Deploying file 'd:\edutec\projets\script\frontend\js\cms\test.txt' to '/test/js/cms (www2.script.lu)' ... [ERROR: '553 Could not create file.']

**Comment by mkloubert** [comment]
@jimschmit 

**Since version 0.52.0**, the extension should be able to auto create non existing directories on a server now.
