### ISSUE TITLE
Mappings setting not including hidden files

### ISSUE THREAD

**Issue by jimschmit** [mkloubert/vscode-deploy-reloaded#28]
### Description

Hello, I have  a .htaccess file for my server that I also want to deploy.
My mapping looks like this now to make it work:
```json
"dir": "/htdocs/",
				"mappings": {
					"frontend/**/*": "/",
					"frontend/.htaccess": "/",
				}
```
But  shouldn't this config also work when I only use "frontend/**": "/" ?
Without the second line, it creates a frontend folder inside the htdocs folder...

**Comment by mkloubert** [comment]
@jimschmit 

I think it has to do with the format of [glob patterns](https://github.com/isaacs/node-glob).

The first pattern does not match with `.htaccess`, because the file starts with a dot, so you have to define it explicitly, I think.

**Comment by mkloubert** [comment]
@jimschmit 

**I changed the behavior in version 0.52.1**, so [folder mappings](https://github.com/mkloubert/vscode-deploy-reloaded/wiki/folder_mappings) will work as expected with "dot files" now, or in other words: you do not need the 2nd pattern anymore.

I forgot to set required options (like `dot` and `nocase`), when using [minimatch](https://github.com/isaacs/minimatch) module.
