### ISSUE TITLE
umask overriden 

### ISSUE THREAD

**Issue by FrColin** [mkloubert/vscode-deploy-reloaded#3]
### Description

I have a sftp target , the deploy is OK but the files modes on unix is 666 rw-rw-rw
the umask as no effect on the deploy .

### Actual behavior

the sftp deploy override the umask set on the account

### Expected behavior

the sftp should respect the umask , the expected mode shoud be rw-r---r-- with a umask 022

### Your environment

- Operating system: Windows 10 , target linux
- Visual Studio Code version: 1.19.1
- Extension version: 0.14.2

**Comment by mkloubert** [comment]
@FrColin 

**I have released version 0.15.0** with new `modes` property.

```json
{
    "deploy.reloaded": {
        "targets": [
            {
                "name:": "MY_SFTP2",
                "type": "sftp",

                "modes": 22
            },

            {
                "name:": "MY_SFTP1",
                "type": "sftp",

                "modes": {
                    "/**/*.php": 666,
                    "/**/*.txt": 22,
                }
            }
        ]
    }
}
```

The first target will set mode to `22` for ALL files.

The second target uses [mimimatch patterns](https://github.com/isaacs/minimatch) to define the modes.

**Comment by FrColin** [comment]
Many Thanks , it is working well

**Comment by rehlers** [comment]
wow this was timely! thanks for this update, I am making use of it as well.
