### ISSUE TITLE
sftp deployment fails on windows

### ISSUE THREAD

**Issue by seatrout** [mkloubert/vscode-deploy-reloaded#31]
### Description

I cannot get the extension to recognise a private key for SFTP deployment; the log file shows a mysterious ENOENT error

### Actual behavior
All attempts to log me in to a linux server using a private key fail with the message 
`[ERROR] Could not deploy files to 'Birdcam': 'All configured authentication methods failed'`

### Expected behavior

Attempts to upload a file to a linux server using SFTP configured to log me in with a private key should work. I have tried every possible relative and absolute path to these keys, which work perfectly well when invoked with putty or ssh from the command line

### Steps to reproduce

Attempt to upload a file. This will happen

#### Example config

```json
{
    "deploy.reloaded": {
        "targets": [
            {
                "type":"sftp",
                "name":"Moode",
                "description":"the test script",
                "dir":"/home/pi/scripts/",
                "host":"192.168.1.66",
                "port":22,
                "user":"pi", 
               // "agent":"pageant",
                "privatekey":"/ssh/for_moode_id_rsa"
            },
            {
                "type":"sftp",
                "name":"Birdcam",
                "description":"camerazero",
                "dir":"/home/pi/scripts/",
                "host":"192.168.1.12",
                "port":22,
                "user":"pi", 
                //"agent":"pageant",
                "privatekey":"/ssh/camerazero_id_rsa"
            }
        ],
     "packages": [
            {
             "name":"package",
             "files":["**/*.py"]
             }  
        ] 
    }
}
```

#### Logs

```
INFO extension.deploy.reloaded.loadplugins - [27/Feb/2018:07:13:03 +0000] "Loaded 19 plugins:
- app
- azureblob
- batch
- compiler
- dropbox
- each
- ftp
- list
- local
- mail
- map
- prompt
- s3bucket
- script
- sftp
- slack
- switch
- test
- zip
"
INFO extension.deploy.reloaded.loadplugins - [27/Feb/2018:08:47:16 +0000] "Loaded 19 plugins:
- app
- azureblob
- batch
- compiler
- dropbox
- each
- ftp
- list
- local
- mail
- map
- prompt
- s3bucket
- script
- sftp
- slack
- switch
- test
- zip
"
TRACE extension.deploy.reloaded.currentfileorfolder - [27/Feb/2018:09:13:57 +0000] "ENOENT: no such file or directory, lstat 'C:\8\settings.json'

Stack:
    at NEW_CONSOLE_LOGGER.addAction (C:\Users\Andrew\.vscode\extensions\mkloubert.vscode-deploy-reloaded-0.53.1\out\log.js:313:52)
    at ActionLogger.<anonymous> (C:\Users\Andrew\.vscode\extensions\mkloubert.vscode-deploy-reloaded-0.53.1\out\log.js:245:25)
    at Generator.next (<anonymous>:null:null)
    at C:\Users\Andrew\.vscode\extensions\mkloubert.vscode-deploy-reloaded-0.53.1\out\log.js:23:71
    at Promise (<anonymous>:null:null)
    at __awaiter (C:\Users\Andrew\.vscode\extensions\mkloubert.vscode-deploy-reloaded-0.53.1\out\log.js:19:12)
    at ActionLogger.onLog (C:\Users\Andrew\.vscode\extensions\mkloubert.vscode-deploy-reloaded-0.53.1\out\log.js:225:16)
    at ActionLogger.<anonymous> (C:\Users\Andrew\.vscode\extensions\mkloubert.vscode-deploy-reloaded-0.53.1\out\log.js:117:95)
    at Generator.next (<anonymous>:null:null)
    at C:\Users\Andrew\.vscode\extensions\mkloubert.vscode-deploy-reloaded-0.53.1\out\log.js:23:71
    at Promise (<anonymous>:null:null)
    at __awaiter (C:\Users\Andrew\.vscode\extensions\mkloubert.vscode-deploy-reloaded-0.53.1\out\log.js:19:12)
    at ActionLogger.log (C:\Users\Andrew\.vscode\extensions\mkloubert.vscode-deploy-reloaded-0.53.1\out\log.js:110:16)
    at ActionLogger.trace (C:\Users\Andrew\.vscode\extensions\mkloubert.vscode-deploy-reloaded-0.53.1\out\log.js:143:14)
    at Object.<anonymous> (C:\Users\Andrew\.vscode\extensions\mkloubert.vscode-deploy-reloaded-0.53.1\out\commands.js:385:18)
    at Generator.throw (<anonymous>:null:null)
    at rejected (C:\Users\Andrew\.vscode\extensions\mkloubert.vscode-deploy-reloaded-0.53.1\out\commands.js:21:65)
    at <anonymous>:null:null"

```

#### Screenshot

{Please write here, if possible}

### Your environment

- Operating system: Windows 10 Home 
- Visual Studio Code version: Version 1.20.0

- Extension version: 0.53.1

### Additional comments

I have no idea where the file that can't be found ought to be, or which configuration setting contains it

**Comment by mkloubert** [comment]
@seatrout

Try set tryKeyboard setting in target to (true).

**Comment by seatrout** [comment]
Nope: same error. But then the sshd daemon on the server is configured only to allow private key logins

**Comment by seatrout** [comment]
Ooops: checking this, the server does allow password authentication. I thought I had stopped that. But the machine is only accessible from inside the network so it should be safe

**Comment by seatrout** [comment]
I'm sorry for these stupid questions but I can't see what's gone wrong
Does the sftp subsystem want an openSSH format key? 
Is there a worked example showing how to translate an absolute Windows file path into something this extension understands? 
Is there any way to log a more informative error message so we know why the authentication fails?

**Comment by mkloubert** [comment]
Use a path like c:/ssh/camerazero_id_rsa for private key on windows ... relative paths should have a leading . like ./ssh/camerazero_id_rsa ... relative paths are mapoed to your .vscode or your .vscode-deploy-reloaded sub folder inside your home directory

**Comment by seatrout** [comment]
No: still doesn't work. With the key id_rsa placed in the ssh subfolder of
` .vscode-deploy-reloaded` in my home dir (next to the logs subfolder)
and the relevant line
`  "privatekey":"./ssh/id_rsa"`
in my workplace configuration, I get the same error message. 

Connecting with an ssh program using the same key from the same computer works perfectly well ...
Should I be restarting the editor between edits to the configuration?

**Comment by seatrout** [comment]
I think this has to be a bug introduced into vscode itself somehow. I have tried other extensions and they won't work, but sftp from the command line in the terminal of vscode works perfectly well. And there are complaints [here](https://github.com/liximomo/vscode-sftp/issues/101) of this functionality breaking with the upgrade to vscode 1.20.

I may try deleting and reinstalling all of the vscode config, but that seems a bit drastic

**Comment by zamkevich** [comment]
@seatrout You have an error in the configuration file.
wrong: "private**k**ey":"…"
right: "private**K**ey":"…"

look it: (a little patience please)
![2018-03-03_01-39-20](https://user-images.githubusercontent.com/13717428/36907856-63dd2bba-1e85-11e8-8358-68c369ead41b.gif)

**Comment by mkloubert** [comment]
@zamkevich @seatrout 

Now the error makes sense!

My eyes are too old for such typos :D

**Comment by seatrout** [comment]
Thank you, both for finding my mistake, and taking the trouble to animate the solution. It's all working now. I will in future trust the intellisense rather than simply typing!
A
