### ISSUE TITLE
sftp modes not applying to file not in a sub-directory

### ISSUE THREAD

**Issue by bewster** [mkloubert/vscode-deploy-reloaded#32]
### Description

When deploying a file that is not in a directory the mode does not appear to change.
If I move the file into a directory, within the workspace, the new mode is set.

### Actual behavior

The attributes of the uploaded file are not changed.
No error is reported; response is ... [OK]

### Expected behavior

File attributes should change.

### Steps to reproduce

Upload a file in the root of the workspace.

#### Example config

```json
{
    "deploy.reloaded": {
        "targets": [
            {
                "name": "Device",
                "type": "sftp",
                "host": "device",
                "dir": "/root",
                "user": "root",
                "password": "xxx"
            }
        ]
    }
}
```

#### Logs

```
Deploying file '...' to '/. (Device)' ... [OK]
```

#### Screenshot

{Please write here, if possible}

### Your environment

- Operating system: Debian Jessie (running in Docker container)
- Visual Studio Code version: 1.20.1
- Extension version: 0.53.1

### Additional comments

The target device is an embedded board running Debian Jessie.

I am cross-compiling an executable and using your extension to upload the file.
As a workaround I have changed the makefile to store the target in a folder.

**Comment by mkloubert** [comment]
@bewster 

According to [that issue](https://github.com/mkloubert/vscode-deploy-reloaded/issues/33) it seems to be a bug.

**Can you update to the latest version (0.53.3) and try it again?**

If you still have problems: Can you check your logs as described [here](https://github.com/mkloubert/vscode-deploy-reloaded/issues/33#issuecomment-370148171) after you have uploaded files that should match?

**Comment by bewster** [comment]
Thanks, I finally started a new workspace and can confirm the issue is resolved.
