### ISSUE TITLE
SFTP target does not obey specified "modes" setting

### ISSUE THREAD

**Issue by robert914** [mkloubert/vscode-deploy-reloaded#33]
### Description

I've tried to use "modes" globally (just a single value), and with specific file mapping. No matter what I try, the files always deploy with 0777 file mode.

### Actual behavior

Using this:

```json
        "targets": [
            {
                "type": "sftp",
...
                "modes": 644
            }
        ]
```

All files that deploy still have file mode 0777 on the remote.

I have also tried:

```json
                "modes": [ "**": 644 ]
```

and just with a single file:

```json
                "modes": [ "readme.txt": 644 ]
```

### Expected behavior

All files that deploy should have file mode 0644 on the remote.
All cases above fail.

### Steps to reproduce

Use an SFTP target, set "modes" to 0644.

#### Example config

```json
    "deploy.reloaded": {
        "packages": [
            {
                "name": "Local",
                "description": "Local source",
                "deployOnSave": [
                    "SRVR"
                ],
                "files": [
                    "**/*",
                    "**/.*"
                ]
            }
        ],
        "targets": [
            {
                "type": "sftp",
                "name": "SRVR",
                "description": "Remote target",
                "host": "myserver.domain.com",
                "port": 22,
                "user": "myuser",
                "privateKey": "${homeDir}/.ssh/id_rsa_mykey",
                "dir": "/some/path/on/my/remote",
                "modes": 644
            }
        ]
    }
```

#### Logs

```
Deploying file '/Users/myuser/src/localwork/readme.txt' to '/. (SRVR)' ... [OK]
```

#### Screenshot

Not applicable.

### Your environment

- Operating system: MacOS 10.12.6, remote server Linux RHEL 6.5
- Visual Studio Code version: 1.20.1
- Extension version: 0.53.1

### Additional comments

I have also tried the original "Deploy" extension, and it correctly handles the "modes" option when I use it instead. However, I prefer to use the new "Reloaded" version as it has more command / features that I prefer.

**Comment by mkloubert** [comment]
@robert914 

**The bug should be fixed since version 0.53.3.**

I added some additional logging for that.

If you still have problems, you should take a look inside the extension logs, which are stored inside your home directory (`.vscode-deploy-reloaded/.logs`).

You can activate additional SFTP logging, by setting `debug` to `(true)`:

```json
{
    "deploy.reloaded": {
        // ...

        "targets": [
            {
                "type": "sftp",
                "name": "SRVR",
                
                "debug": true,

                // ...
            }
        ]
    }
}
```

This should also catch any log produced by [ssh2-sftp-client](https://github.com/jyu213/ssh2-sftp-client) and write them to the extension log files.

**Comment by mkloubert** [comment]
@robert914 

Seems to be the same bug as described [here](https://github.com/mkloubert/vscode-deploy-reloaded/issues/32) by @bewster

**Comment by robert914** [comment]
Ok, I installed 0.53.3 and it seems to be working correctly now!
Thanks for the fast response!!

**Comment by robert914** [comment]
Also, thanks for the debug / logs tip. I was not aware of that option. I'll use it in the future if I see issues. Thanks again!
