### ISSUE TITLE
mappings drop folder

### ISSUE THREAD

**Issue by Mordef** [mkloubert/vscode-deploy-reloaded#39]
Have 2 Mappings:
```
"mappings": { 
      "webs/dev/site/**/*"    : "/HAimperia/apache-develop/site",
      "webs/dev/htdocs/**/*"  : "/HAimperia/apache-develop/htdocs"
  }
```

All for htdocs work fine, but in site, evrything goes to /HAimperia/apache-develop/site, nu subfolders

Log:
This is ok:
Stelle Datei '...\webs\dev\htdoc\static\shared\css\header.css' in '/HAimperia/apache-develop/htdocs/static/shared/css (vm-fuh)' bereit ... [OK]

Thats wrong:
Stelle Datei '...\webs\dev\site\metafiles\universitaet.meta' in **'/HAimperia/apache-develop/site** (vm-fuh)' bereit ... [OK]

Target must /HAimperia/apache-develop/site/metafiles

Tested with some other files:
Stelle Datei ...\webs\dev\site\include\shared\config.inc' in '/HAimperia/apache-develop/site/shared (vm-fuh)' bereit ... [OK]

"include" is missing oon target.

Stelle Datei '...\webs\dev\site\modules\core\Project\Shared\Export.pm' in '/HAimperia/apache-develop/site/core/Project/Shared (vm-fuh)' bereit ... [OK]

"modules" is missing on target.
Looks like only the fiirst folder where dropped.

Also i have testedd with other mappings: "webs/dev/**/*": "/HAimperia/apache-develop"

Now the htdocs is missing:
Stelle Datei '...\webs\dev\htdocs\static\shared\css\header.css' in '/HAimperia/apache-develop/static/shared/css (vm-fuh)' bereit ... [OK]

This mappings where working correct, but target on /dev/**/* on .../site is bad.
```
                    "mappings": {
                        "webs/dev/htdocs/**/*"  : "/HAimperia/apache-develop/htdocs",
                        "webs/dev/**/*": "/HAimperia/apache-develop/site",
                    }
```

**Comment by mkloubert** [comment]
@Mordef 

As workarround, you can try the following:

```json
"mappings": {
    "webs/dev/site": "/HAimperia/apache-develop/site",
    "webs/dev/site/**/*"    : "/HAimperia/apache-develop/site",
    "webs/dev/htdocs"  : "/HAimperia/apache-develop/htdocs",
    "webs/dev/htdocs/**/*"  : "/HAimperia/apache-develop/htdocs"
}
```

I think it has to do with format of [glob](https://github.com/isaacs/node-glob) and [minimatch](https://github.com/isaacs/minimatch) patterns.

**Comment by Mordef** [comment]
Yes, that works and looks better then my before.
