### ISSUE TITLE
Prebuild process

### ISSUE THREAD

**Issue by FrColin** [mkloubert/vscode-deploy-reloaded#4]
### Feature Request

A nice to have feature, might be a "prebuild" before deploy 
for example before deploy , I need to build a production version
using a npm script like "prod": "ng build --aot=true --build-optimizer --environment prod --prod "
this would produce a dist repository , that I deploy to production server.
so the prebuild commands might be something like 

"prebuilds" : {
     "npm run prod"
}

**Comment by mkloubert** [comment]
@FrColin 

You can use a [target operation](https://github.com/mkloubert/vscode-deploy-reloaded/wiki/target_operations#exec-) for this:

```json
{
    "deploy.reloaded": {
        "targets": [
            {
                "type": "sftp",

                "beforeDeploy": [
                    {
                        "type": "exec",
                        "target": "npm run prod"
                    }
                ]
            }
        ]
    }
}
```

**Comment by FrColin** [comment]
Ok , RTFM ;-) 
is the right syntax is command instead of target ?
"beforeDeploy": [
                    {
                        "type": "exec",
                        "command": "npm run prod"
                    }
                ]
typo in the doc example ?

**Comment by mkloubert** [comment]
@FrColin 

Oh, right a typo.

It's `command` and NOT `target`. Thanks!
