### ISSUE TITLE
Info on done

### ISSUE THREAD

**Issue by Mordef** [mkloubert/vscode-deploy-reloaded#42]
atm we see only the message in output.
If u save multiple times same file, you cant't see if file deployed.

Can u insert something like this?

deploy.js: 451
`vscode.window.showInformationMessage( ME.t('deploy.deployingFile', F, destination) );`

**Comment by mkloubert** [comment]
@Mordef 

**I have released a new version 0.59.0**, which is now able to display a popup after a deploy operation.

For that, you only need to setup the [global settings](https://github.com/mkloubert/vscode-deploy-reloaded/wiki#settings--) `showPopupWhenFinished` and `showPopupOnSuccess`:

```json
{
    "deploy.reloaded": {
        "showPopupWhenFinished": 1,
        "showPopupOnSuccess": false,

        // ...
    }
}
```

This will show a popup, after at least 1 file has been handled, but NOT on success (`showPopupOnSuccess` = `(false)`).

You can also use a boolean for `showPopupWhenFinished` instead:

```json
{
    "deploy.reloaded": {
        "showPopupWhenFinished": true,
        "showPopupOnSuccess": true,

        // ...
    }
}
```

This will show a popup, after at least 2 filse have been handled.

The default value of `showPopupOnSuccess` is `(true)` btw.
