### ISSUE TITLE
Enhance notification text for showPopupOnSuccess

### ISSUE THREAD

**Issue by robert914** [mkloubert/vscode-deploy-reloaded#47]
### Description

The new showPopupOnSuccess/showPopupWhenFinished options are really helpful! Thanks for that. I'd like to ask / recommend an improvement to the notification that's posted:

- If there was only one file deployed/pulled (i.e. using showPopupWhenFinished=1) which usually happens when you also have deployOnSave/deployOnChange=true, can the notification include the relative workspace file path in the notification?

- If there were > 1 file deployed/pulled, can the notification include how many files were deployed/pulled (since you can't list them all in the notification, it would be too large in many cases).

### Actual behavior

- Current notifications look like:
[vscode-deploy-reloaded]::[project1] All files have been deployed.
[vscode-deploy-reloaded]::[project1] All files have been pulled.

### Requested behavior

- For single-file case:
[vscode-deploy-reloaded]::[project1] File the/deployed/file.css has been deployed.
[vscode-deploy-reloaded]::[project1] File the/deployed/file.css has been pulled.

- For multiple file case:
[vscode-deploy-reloaded]::[project1] Total of 5 files have been deployed.
[vscode-deploy-reloaded]::[project1] Total of 5 files have been pulled.

### Steps to reproduce

Not a bug. Just a request.

#### Example config

```json
{
    "deploy.reloaded": {
...
        "showPopupOnSuccess": true,
        "showPopupWhenFinished": 1,
...
    }
}
```

#### Logs

Not applicable.

#### Screenshot

Not applicable.

### Your environment

- Operating system: MacOS X 10.12.6
- Visual Studio Code version: 1.21.1
- Extension version: 0.60.0

### Additional comments

Thanks!

**Comment by mkloubert** [comment]
@robert914 

**Since version 0.61.0**, you should have better popup messages.

**Comment by robert914** [comment]
Thanks! This helps!

However, I have one issue, and one adjustment request:

1. The path shown for the single file case is the full path to the file. Can you only show the relative path to the project/workspace?

2. I also noticed that the popup already shows what extension the message comes from in the expanded view at the bottom like this:

Source: Deploy (Reloaded) (Extension)

Would it be possible to remove the "[vscode-deploy-reloaded]::" part on the front of the notification, since it's not really necessary?

Thanks!!

**Comment by mkloubert** [comment]
@robert914 @Mordef

Right, much better!

**Should be available since version 0.62.1 now.**

**Comment by robert914** [comment]
I updated to 0.62.1, but I don't see any difference in the notifications?

**Comment by mkloubert** [comment]
@robert914 @Mordef

Sorry, I forgot to merge from branch.

**The feature should be available since the new version 0.62.2 now.**

**Comment by robert914** [comment]
Ok, I updated to 0.62.3. I see the paths are now relative, so my (1) item above is now resolved! Thanks!

However, it still shows the extension prefix "[vscode-deploy-reloaded]::" in the notification, were you going to remove that as well? Or was my (2) item not going to be changed?

Thanks!

**Comment by mkloubert** [comment]
@robert914 

**The prefix should be removed since version 0.63.0.**

**Comment by robert914** [comment]
Awesome! Works perfectly! Thanks!!
