### ISSUE TITLE
Deploying file '' to '' ... message is missing target name.

### ISSUE THREAD

**Issue by rehlers** [mkloubert/vscode-deploy-reloaded#5]
### Description

When deploying code, the message Deploying file 'xxxx' to 'xxxx' does not include the target name. This would be very useful for me, especially when deploying the same file to multiple targets via a batch.

### Actual behavior

Deploying file '[whatever]/pp/test.py' to '/usr/local/etc/pp' ... [OK]

### Expected behavior

Deploying file '[whatever]/pp/test.py' to '/usr/local/etc/pp (server02)' ... [OK]

### Steps to reproduce

Deploy a single file to a SFTP (or batch) target.

#### Example config

```json
{
    "deploy.reloaded": {
        // your config
    }
}
```

### Screenshot

See actual vs expected above

### Your environment

- Operating system: MacOS 10.12.6
- Visual Studio Code version: 1.19.1
- Extension version: 0.15.0

### Additional comments

**If I update the deploy.ts:**
```
LF.onBeforeUpload = async function(destination?: string) {
   if (arguments.length < 1) {
      destination = `${deploy_helpers.toDisplayablePath(NAME_AND_PATH.path)} (${TARGET_NAME})`;
   }
   else {
      destination = `${deploy_helpers.toStringSafe(destination)}`;
   }
```

**to change the last destination line to:**
```
destination = `${deploy_helpers.toStringSafe(destination)} (${TARGET_NAME})`;
```
Then I get the output I would like to see for a single target. However, if I am doing a batch mode, then the target name is the name of the batch target, instead of each individual target being cycled through. It would be great if when I do a batch deploy, I can see each target being uploaded to by name.

**Comment by mkloubert** [comment]
Thats right ... this is much better.

**I released this with version 0.16.0.**

**Comment by rehlers** [comment]
Thanks again for the amazingly fast updates on this!

One more thing with this, the 0.16.0 change still has the name of the batch target instead of each individual server. Not sure how hard that would be to fix ... right now I get output like this:

Deploying file '/Users/robehlers/Documents/misc/nr_inventory.py' to '/usr/local/paypal (All Servers)' ... [OK]
Deploying file '/Users/robehlers/Documents/misc/nr_inventory.py' to '/usr/local/paypal (All Servers)' ... [OK]

It would be cool with batch targets if each target being cycled through was listed instead, more like this:

Deploying file '/Users/robehlers/Documents/misc/nr_inventory.py' to '/usr/local/paypal (server01)' ... [OK]
Deploying file '/Users/robehlers/Documents/misc/nr_inventory.py' to '/usr/local/paypal (server02)' ... [OK]

**Comment by mkloubert** [comment]
**Since version 0.16.1** the extension uses the format

`[REAL_TARGET_NAME] [DESTINATION] ([BATCH_TARGET_NAME])`

as info message for "batch" targets.

This will show you:

1. The real target
2. That a file is deployed via a "batch" target

**Comment by rehlers** [comment]
that is perfect, thank you so much for continuing to make this extension useful. Just in the past 24 hours you've made it go from good to perfect for my needs!
