### ISSUE TITLE
Extension stop working

### ISSUE THREAD

**Issue by vystepanenko** [mkloubert/vscode-deploy-reloaded#50]
### Description

After update my VSC to new version extension stop working.
I have list of all commands but no one working

#### Logs

```
command 'extension.deploy.reloaded.deploy' not found

```

#### Screenshot
list of command
![default](https://user-images.githubusercontent.com/22811452/37644708-5635022a-2c2d-11e8-8f0c-3a54a3ec9bc2.png)

Error
![default](https://user-images.githubusercontent.com/22811452/37644525-c7f01d56-2c2c-11e8-9e8a-d6b76cf7bc97.png)

### Your environment

- Operating system:Windows 10
- Visual Studio Code version: Version 1.21.1
Commit 79b44aa704ce542d8ca4a3cc44cfca566e7720f1
Date 2018-03-14T14:46:47.128Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
- Extension version: v0.64.0

### Additional comments

I already tried to disable/enable extension and reinstall it. Nothing helps

**Comment by mkloubert** [comment]
@vystepanenko 

I cannot reproduce the issue.

Can you try to [install one of an older version](https://github.com/mkloubert/vscode-deploy-reloaded#install-offline-) from [release](https://github.com/mkloubert/vscode-deploy-reloaded/releases section)?

**Comment by vystepanenko** [comment]
@mkloubert 
thanks for quick reply
I installed 0.63.1. After that my VSC automatically updated it to 0.64.0 and everything start working


just mystique :)
