### ISSUE TITLE
Help for the deployOnSave 

### ISSUE THREAD

**Issue by pihomeserver** [mkloubert/vscode-deploy-reloaded#55]
### Description

The deployment of files (from the mask i want to deploy all files) is not fired automatically

### Actual behavior

The deployment of files is not fired automatically

### Expected behavior

The deployment works if fired manually but i would like to have it executed automatically

#### Example config

```json
{
    "git.ignoreLimitWarning": true,
    "deploy.reloaded": {
        "packages": [
            {
                "name": "ABC",
                "description": "ABC",
                "deployOnSave": {
                    "files": [
                        "**/*.*"
                    ],
                    "targets": [ "ci-dev (ABC)" ]
                }
            }
        ],
        "targets":  [
            {
                "type": "sftp",
                "name": "ci-dev (ABC)",
                "description": "ci-dev (ABC)",
                "dir": "/home/chris/ABC",
                "host": "192.168.10.160", "port": 22,
                "user": "chris", "password": "mypassword"
            }
        ]
    }
}
```

### Your environment

- Operating system: MacOs High Sierra 10.13.4 beta
- Visual Studio Code version: 1.21.1
- Extension version: 0.67.1

**Comment by pihomeserver** [comment]
@mkloubert thank you for your help. It's still not working.
To try to move forward, i made few tests like removing previous version of the extension, changing parameters but unsuccessfully 

When opening VS code, the extension is well started even if the default workspace selected is the first one and not the one of the selected file. I have to switch to another file and come back on the previous one the have the good workspace selected

Then when i update a file and save it. The output console remains empty
The configuration is set at the folder level. Not user or workspace levels (i'm not sure where to set it as i am new at VScode, coming from webstorm)

**Comment by pihomeserver** [comment]
By the way it works with old extension with a specific configuration defined for each folder of the workspace

**Comment by Eddcapone** [comment]
@mkloubert I can confirm, it does not work for me either. I always have to manually deploy. Please fix this bug.

**Comment by mkloubert** [comment]
@Eddcapone @pihomeserver 

I close this here ... we should continue the discussion in [issue #72](https://github.com/mkloubert/vscode-deploy-reloaded/issues/72).
