### ISSUE TITLE
Can't figure out how to map relative local directory

### ISSUE THREAD

**Issue by knetworx** [mkloubert/vscode-deploy-reloaded#56]
### Description

I can't seem to figure out how to map a relative local directory to a remote directory with a different name. I have a full project containing PHP files that belong on one server, AS3 files that run locally, Scala files that belong on another server, etc. I want to deploy the files in a sub-directory to a directory on a remote host with a different name.

I have VS code open at project_root, and I want to deploy project_root/framework local directory to /opt/cc/wc on the remote host, such that project_root/framework/myfile.php would end up on the remote host at /opt/cc/wc/myfile.php

I've figured out that if I open VS code within the framework directory, I only need to set `"dir":"/opt/cc/wc"` in the target and everything works as expected. But when I'm opening VS code at project_root, I can't seem to figure out what combination of dir, mapping, etc. necessary to get that same behavior.

### Actual behavior

Error popup with the text: "Could not compare current file: 'No such file'"

### Expected behavior

Side-by-side comparison of the local and remote file.

### Steps to reproduce

Attempt to compare the local file to the remote file.

#### Example config

Here is the config which functions as expected when I open VS Code within the framework folder (project_root/framework/.vscode/settings.json):
```json
{
    "deploy.reloaded": {
        "packages": [
            {
                "name": "Framework Files",
                "files": [
                    "**/*.php"
                ]
            }
        ],
        "targets":[
            {
                "type": "sftp",
                "name": "Sandbox",
		"description": "Deploy PHP files to Sandbox",
                "dir": "/opt/cc/wc",
                "host": "<myservername>", "port": 22,
                "user": "<myusername>",
		"privateKey": "<myprivatekey>",
		"privateKeyPassphrase": "<myprivatekeypassphrase>"
            }
        ]
    }
}
```
What would I need to put in project_root/.vscode/settings.json to get the same behavior when I open VS Code at the root?

#### Logs

I can't figure out how to view the logs either. I just downloaded this extension an hour ago, so maybe it's obvious and I'm just missing something.

**Comment by mkloubert** [comment]
@knetworx 

Have a look at the wiki article [Folder mappings](https://github.com/mkloubert/vscode-deploy-reloaded/wiki/folder_mappings).

In your case, your configuration should look like that:

```json
{
    "deploy.reloaded": {
        // ...

        "targets":[
            {
                // ...

                "dir": "/opt/cc/wc",

                "mappings": {
                    "/framework/**/*": "/"
                }

                // ...
            }
        ]
    }
}
```

This will map all files inside `/framework` to the relative remote folder `/`, which is relative to the value of `dir` property.

**Comment by knetworx** [comment]
AHA! Thank you! That did it. I tried various combinations in the mappings, but couldn't quite get it right.
