### ISSUE TITLE
latest version not working on windows 10

### ISSUE THREAD

**Issue by filly82** [mkloubert/vscode-deploy-reloaded#58]
### Description

The latest version does not work for me. Whatever command I try to execute it says "command xyz not found". I tried another older versions, just a few, and version 0.63.1 is working for me (0.73.0 is not and 0.72.1 also)

It is kinda weird the the command that does not exist really does not exist in my vscode bindings (but only in 0.73.0, in 0.63.1 there a lot more commands available than in 0.73.0)

![grafik](https://user-images.githubusercontent.com/4948973/39289149-2cfa11c8-492b-11e8-8c99-a86e4434d6fd.png)

![grafik](https://user-images.githubusercontent.com/4948973/39289157-3105ad68-492b-11e8-8170-5a9178d4618d.png)

### Your environment

- Operating system: Windows 10
- Visual Studio Code version: 1.22.2
- Extension version: {Please write here}

Version 1.22.2
Commit 3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9
Datum 2018-04-12T16:38:45.278Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architektur x64

**Comment by mkloubert** [comment]
@filly82 

I am not sure if it something to do with Windows 10. I am working on same OS and it works fine.

Have you tried to

* uninstall the extension
* close VSCode
* remove any "C:\Users\<username>\.vscode\mkloubert.vscode-deploy-reloaded-*" folder?
* start VSCode
* install [the extension](https://marketplace.visualstudio.com/items?itemName=mkloubert.vscode-deploy-reloaded) again

?

**Comment by filly82** [comment]
the removal of the"C:\Users<username>.vscode\EXTENSIONS\mkloubert.vscode-deploy-reloaded-*" folder" did the trick. thank you!
