### ISSUE TITLE
Deploy Merge pull request?

### ISSUE THREAD

**Issue by yousufmj** [mkloubert/vscode-deploy-reloaded#59]
Is it possible to deploy a merge pull request? 
there is an option when choosing a git commit but nothing gets deployed. Either have have to deploy each commit separately or each file separately

**Comment by mkloubert** [comment]
@yousufmj 

You can do the following:

1. Detect changed files by using `Deploy Reloaded: Tools ...` >> `Detect git changes ...`
2. Select a range of commits from a branch
3. A new editor with a list of changed files will be opened
4. Remove and/or change the files you would like to deploy
5. Select the files to deploy in the editor (no selection will deploy all files!)
6. Deploy that selection via `Deploy Reloaded: Deploy ...` >> `File list`

**Comment by yousufmj** [comment]
Thanks @mkloubert - that was very helpful! that works and allows me to commit all my files from my merge.
