### ISSUE TITLE
Waiting for Deploy "local"

### ISSUE THREAD

**Issue by Mordef** [mkloubert/vscode-deploy-reloaded#60]
### Description
Windows networkdrive O: is mapped to \\winserver\dir\
Settings is
"type": "local",
"dir": "O:/"

It works, but after save i have to wait up to 10 seconds before deploy started
I try with "dir" : "\\\\winserver\\dir\\" but its the same.

FTP and SFTP woorks fine and fast

**Comment by Mordef** [comment]
Ok i found it.
Its a Perl project and ctags is updating before deploy.
Any way to change that?
Deploy before ctags?

**Comment by Mordef** [comment]
Sorry to tell, its not ctags. Have disabled it and its still slow.

**Comment by Mordef** [comment]
Same as #55

**Comment by mkloubert** [comment]
@Mordef 

I close this here ... we should continue the discussion in [issue #72](https://github.com/mkloubert/vscode-deploy-reloaded/issues/72).
