### ISSUE TITLE
Suggestion: Monitor file / folder

### ISSUE THREAD

**Issue by gsabater** [mkloubert/vscode-deploy-reloaded#61]
### Description

SFTP for sublime allows users to monitor a file to be uploaded on external saves. This is useful for example when using webpack, we can upload the bundled file after running the script without having to manually go to the file and upload it

### Additional comments

Useful options would be (when possible)
* Monitor a file for external saves
* Monitor a full folder for external saves
* Ability to hook scripts to let us build steps to deploy in some way

**Comment by mkloubert** [comment]
@gsabater 

Monitor remote files / folders or a local ones?

**Comment by mkloubert** [comment]
@gsabater 

Is [deploy on change](https://github.com/mkloubert/vscode-deploy-reloaded/wiki/deploy_on_change), [deploy on save](https://github.com/mkloubert/vscode-deploy-reloaded/wiki/deploy_on_save) and [remove on change](https://github.com/mkloubert/vscode-deploy-reloaded/wiki/remove_on_change) you are looking for?
