### ISSUE TITLE
No FTPS support

### ISSUE THREAD

**Issue by textoo** [mkloubert/vscode-deploy-reloaded#67]
Hello,

i can't find any mention on FTPS support in the wiki, i currently use the former extension and i realy need this feature to switch to the new one.
is this feature is supported or will be supported in a near future ? 

thanks

**Comment by hajekj** [comment]
@mkloubert: Could you please update the wiki to reflect the changes in #70 - I don't seem to be able fork and modify the wiki.

**Comment by mkloubert** [comment]
@hajekj 

Of, course!

I started to integrate your changes ... I hope, I can release them in about 2 hours.

**Comment by mkloubert** [comment]
@textoo

@hajekj implemented secure FTPS support for [ftp targets](https://github.com/mkloubert/vscode-deploy-reloaded/wiki/target_ftp), which **is available since version 0.75.0**.

A simple way to activate it, is to setup your target the following way:

```json
{
    "deploy.reloaded": {
        "targets": [
            {
                "type": "ftp",
                "name": "My secure FTPS folder",

                "engine": "ftp",
                "secure": true,
                "host": "ftps.example.com", "port": 990,

                "dir": "/",
                "user": "<YOUR_USER>", "password": "<YOUR-PASSWORD>"
            }
        ]
    }
}
```

Please let us known, if that works for you.

**Comment by textoo** [comment]
hello , thanks @hajekj and @mkloubert 


just tested it : 
removed former extension, installed the reloaded one, renamed "deploy" section in settings by "deploy.reloaded" 

and get "550 SSL/TLS required on the control channel" warning/error in the output 

i use VSCode 1.24

my obfuscated config :

{
    "deploy.reloaded": {
        "packages": [
            
        ],
        "targets": [
            {
                "name": "preprod",
                "type": "ftp",
                "port": 21,
                "user": "someuser",
                "password": "somepassword",
                "host": "someIP",
                "dir": "/somedirectory",
                "secure": true,
                "rejectUnauthorized": false
                
            },
            {
                "name": "prod",
                "type": "ftp",
                "port": 21,
                "user": "someotheruser",
                "password": "someotherpassword",
                "host": "someIP",
                "dir": "/someotherdirectory",
                "secure": true,
                "rejectUnauthorized": false
                
            }
        ]
    }
}

**Comment by textoo** [comment]
OK, added "engine" : "ftp" and it works! 

good job! :)
