### ISSUE TITLE
deploy all open files also is catching .git file

### ISSUE THREAD

**Issue by rehlers** [mkloubert/vscode-deploy-reloaded#7]
### Description

The new option to deploy all open text files (which is awesome) seems to be including a file from whatever filename is in the active window with '.git' appended. This is just throwing an error on deploy, as it seems the filename is bogus. I tried this multiple times and the ".git" file seems to always be the one file that I have open in the window. This happens if the active file has been Modified or has already been committed into git. 

### Actual behavior

Deploying file '/app/admin/views.py' to '/var/www/app/admin (server-01)' ... [OK]
Deploying file '/app/models.py' to '/var/www/app (server-01)' ... [OK]
Deploying file '/app/admin/forms.py' to '/var/www/app/admin (server-01)' ... [OK]
Deploying file '/app/templates/base.html' to '/var/www/app/templates (server-01)' ... [OK]
Deploying file '/app/admin/templates/admin/main.html' to '/var/www/app/admin/templates/admin (server-01)' ... [OK]
Deploying file '/app/admin/forms.py.git' to '/var/www/app/admin (server-01)' ... [ERROR: 'ENOENT: no such file or directory, open '/app/admin/forms.py.git'']

### Expected behavior

Deploying file '/app/admin/views.py' to '/var/www/app/admin (server-01)' ... [OK]
Deploying file '/app/models.py' to '/var/www/app (server-01)' ... [OK]
Deploying file '/app/admin/forms.py' to '/var/www/app/admin (server-01)' ... [OK]
Deploying file '/app/templates/base.html' to '/var/www/app/templates (server-01)' ... [OK]
Deploying file '/app/admin/templates/admin/main.html' to '/var/www/app/admin/templates/admin (server-01)' ... [OK]

### Steps to reproduce

Open multiple files in VS. Choose deploy All open files. pick a target.

#### Example config

```json
{
    "deploy.reloaded": {
        // your config
    }
}
```

### Screenshot

see actual and expected above

### Your environment

- Operating system: MacOS 10.12.6
- Visual Studio Code version: 1.19.1
- Extension version: 0.16.0

### Additional comments

{Please write here, if there is something more to tell}

**Comment by mkloubert** [comment]
@rehlers 

**The hotfix 0.16.2 should solve the issue.**

**Comment by rehlers** [comment]
Thanks again, you are super awesome at working on this extension! I tested and it is working great now with 0.16.2
