### ISSUE TITLE
Suggestion: Deploy changed files

### ISSUE THREAD

**Issue by jcamachott** [mkloubert/vscode-deploy-reloaded#75]
### Description

So you've made changes to a few different files and you want to upload them...but you don't want to commit to the remote repo just yet...can this extension deploy only the files changed since last commit?

**Comment by mkloubert** [comment]
@jcamachott 

You are able to select `Deploy Reloaded: Deploy` >> `Uncomitted git changes`.

Another way is to open only these files and select `Deploy Reloaded: Deploy` >> `All open files ...`

If you want to deploy a specific range of commits, you have to select `Deploy Reloaded: Deploy` >> `git commit ...`, where you can select one or more commits of a branch.

To detect changes between one or more commit only, you can select `Deploy Reloaded: Tools` >> `Detect git changes`.
This will open a list with the paths of the changed files, relative to your workspace. You can (edit if needed) and select them, to deploy / pull / delete them by selecting `Deploy Reloaded: Deploy` >> `File list` command ... this also works with "pull" and "delete".
