### ISSUE TITLE
Unexpected stop working auto upload

### ISSUE THREAD

**Issue by heminei** [mkloubert/vscode-deploy-reloaded#77]
### Description

When I enable sass compiler or when I pull from git and comes many changes, the deploy plugin disables automatic upload.

Also, I have disabled popup when upload finished, but not working - the popup is showing.

#### User settings
```json
{
    "deploy.reloaded": {
        "timeToWaitBeforeActivateDeployOnChange": 0,
        "timeToWaitBeforeActivateRemoveOnChange": 0,
        "showStatusWhenFinished": true,
        "showPopupWhenFinished": false,
        "showPopupOnSuccess": false,
        "deployOnChangeButton": true,
        "deployOnSaveButton": true,
        "deployOnSave": true,
        "deployOnChange": true,
    },
}
```

#### Workspace settings
```json
{
    "deploy.reloaded": {
        "packages": [{
            "name": "Main",
            "description": "",
            "deployOnChange": true,
            "deployOnSave": true,
            "removeOnChange": true,
            "targets": [
                "dev"
            ]
        }],
        "targets": [{
            "name": "dev",
            "type": "sftp",
            "host": "xxx",
            "user": "xx",
            "password": "xxx",
            "port": 22,
            "description": "",
            "dir": "/xx/xxx/xxx"
        }]
    }
}
```

### Your environment

Windows 10 Pro

Version 1.24.1
Commit 24f62626b222e9a8313213fb64b10d741a326288
Date 2018-06-13T17:51:32.889Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by mkloubert** [comment]
@heminei 

**Should be fixed since version 0.77.0.**

I close that issue ... we should continue discussion in [issue #79](https://github.com/mkloubert/vscode-deploy-reloaded/issues/79).
