### ISSUE TITLE
noneFound error message when clicking on bottom panel

### ISSUE THREAD

**Issue by pythoninja** [mkloubert/vscode-deploy-reloaded#78]
### Description

Useless error message when clicking on Deploy Reloaded button in bottom panel when no workspace was selected.

### Actual behavior

"noneFound.noneFound" error message is displayed.

### Expected behavior

Not sure, please see Actual behavior section.

### Steps to reproduce

1. Add two different folders to your workspace.
2. Close all active editors.
3. You will see yellow text "Deploy Reloaded: (no workspace selected)".
4. Click on it.

#### Screenshot

![screenshot_20180620_190839](https://user-images.githubusercontent.com/13417093/41670578-5a26a022-74bd-11e8-864f-31cd1358aadf.png)

### Your environment

- Operating system: Ubuntu 18.04 LTS
- Visual Studio Code version: 1.24.1
- Extension version: 0.75.1

**Comment by mkloubert** [comment]
@pythoninja 

**I have fixed the bug in version 0.76.1.**

What kind of workspace folders did you add? Are they mapped to local folders or to remote resources, like SFTP using the new [FileSystemProvider API](https://code.visualstudio.com/docs/extensionAPI/vscode-api#FileSystemProvider)?

**Comment by pythoninja** [comment]
@mkloubert, oh, well, it's just a two random local folders.

**Comment by mkloubert** [comment]
Yes, seems to be a bug if these two folders are local.

**Comment by pythoninja** [comment]
@mkloubert should I open another issue or ... ?

**Comment by mkloubert** [comment]
Yes!

**Comment by pythoninja** [comment]
Ok, so will close this. Thanks!
