### ISSUE TITLE
Deploy/Remove on change turns off on multiple files

### ISSUE THREAD

**Issue by Zaczero** [mkloubert/vscode-deploy-reloaded#79]
### Description

Whenever I minify/compile files there is more than one file to upload. This sets the "Deploy on change" and "Remove on change" to sleep and I have to re-enable them manually.

What I noticed is that sometimes the compilation takes a bit longer (delayed?) and instead of 2 deploy pop-ups showing instantly there is a small delay (100ms?) between them and the "Deploy on change" doesn't break and both files are deployed successfully.

### Actual behavior

Deploy/Remove on change goes to sleep whenever you minify/compile and generate more than 1 file.

### Expected behavior

Deploy/Remove on change stays enabled all the time. Only user can change the state.

### Steps to reproduce

1. Install an extensions that will minify css/js files.
2. Set minify method on save.
3. Save the css/js file

#### Example config

```json
{
    "deploy.reloaded": {
        "deployOnChangeButton": true,
        "removeOnChangeButton": true,
    }
}
```

#### Logs

```
// the rest of the logs are the same but with different time so I don't see a reason to upload them all (takes a lot of vertical space)
INFO extension.deploy.reloaded.loadplugins - [24/Jun/2018:18:16:23 +0000] "Loaded 19 plugins:
- app
- azureblob
- batch
- compiler
- dropbox
- each
- ftp
- list
- local
- mail
- map
- prompt
- s3bucket
- script
- sftp
- slack
- switch
- test
- zip
"
INFO workspaces.workspace.reloadpackagebuttons() - [24/Jun/2018:18:16:23 +0000] "Registrated command 'extension.deploy.reloaded.buttons.deployPackage-9007199254740991' for button of package '(Package #1)'."
INFO workspaces.workspace.reloadpackagebuttons() - [24/Jun/2018:18:17:08 +0000] "Registrated command 'extension.deploy.reloaded.buttons.deployPackage-9007199254740990' for button of package '(Package #1)'."
```

#### Screenshot

![](https://prtsc.me/i/74fc1dbb.jpeg)
First two were okay and the last one broke the deploy on change state.

![](https://prtsc.me/i/5c00371b.jpeg)
(broken new lines?)

![](https://prtsc.me/i/ed8f914e.jpeg)
(after drag-n-drop 20 files - bug occured)

![GIF](https://prtsc.me/c/deploy1.gif)
^ direct link (preview breaks for me?) https://prtsc.me/c/deploy1.gif

### Your environment

- Operating system: Windows 10 Pro 17134
- Visual Studio Code version: 1.24.1
- Extension version: 0.76.1

### Additional comments

I think it's the similar issue to #77.

**Comment by mkloubert** [comment]
@Zaczero @heminei

**Should be fixed since version 0.77.0.**

Please let me know if it works for you now.

The next thing try to improve, is the speed ... because in my scenario I copied about 200 files which triggers 200 file changes at the same time and would freeze the GUI.

**Comment by heminei** [comment]
Thank you! It works.

**Comment by Zaczero** [comment]
Did some tests and looks like it's fixed now. Thank you so much! 🎉 🎉
