### ISSUE TITLE
Suggestion: Pulling with deployOnChange enabled shouldn't deploy the pulled files

### ISSUE THREAD

**Issue by Zaczero** [mkloubert/vscode-deploy-reloaded#83]
### Description

Whenever I pull the file with deployOnChange enabled, the same file gets deployed a second after.  
I understand that this is how the deployOnChange works but it's taking some extra time to deploy the same files that are already on the remote.

### Actual behavior

Pulling with deployOnChange enabled deploys the pulled file to the remote.

### Expected behavior

Pulling with deployOnChange enabled turns off? deployOnChange for a few seconds until the pull is done.

*or*

deployOnChange should be smart enough to ignore freshly pulled files.

### Steps to reproduce

1. Turn on deployOnChange
2. Pull the file

#### Example config

```json
{
    "deploy.reloaded": {
        "deployOnChangeButton": true,
        "removeOnChangeButton": true,
        "packages": [
            {
                "button": {
                    "text": "Deploy",
                    "targets": [
                        "target_ftp",
                    ],
                }
            }
        ],
        "targets": [
            {
                "name": "target_ftp",

                "type": "sftp",
                "dir": "***",

                "host": "***",
                "user": "***",
                "privateKey": "***",
                "askForPrivateKeyPassphrase": true,
            }
        ],
    }
}
```

#### Logs

```
INFO extension.deploy.reloaded.loadplugins - [24/Jun/2018:18:16:23 +0000] "Loaded 19 plugins:
- app
- azureblob
- batch
- compiler
- dropbox
- each
- ftp
- list
- local
- mail
- map
- prompt
- s3bucket
- script
- sftp
- slack
- switch
- test
- zip
"
```

#### Screenshot

![](https://prtsc.me/i/9745427c.jpeg)

### Your environment

Operating system: Windows 10 Pro 17134
Visual Studio Code version: 1.24.1
Extension version: 0.81.1

### Additional comments

Just a suggestion. It doesn't look like a bug for me 👍

**Comment by mkloubert** [comment]
@Zaczero 

You should try the `pauseFilesFor` setting for [packages](https://github.com/mkloubert/vscode-deploy-reloaded/wiki#packages-):

```json
{
    "deploy.reloaded": {
        "packages": [
            {
                "name": "My project",

                "pauseFilesFor": 2000,
                
                "deployOnChange": true,

                "files": [
                    "**/*.css",
                    "**/*.js"
                ],

                "targets": [ "My test target" ]
            }
        ],

        // ...
    }
}
```

This will wait 2 seconds, before reactivate an auto deploy operation for a file ([deploy on change](https://github.com/mkloubert/vscode-deploy-reloaded/wiki/deploy_on_change) or [remove on change](https://github.com/mkloubert/vscode-deploy-reloaded/wiki/remove_on_change)).
