### ISSUE TITLE
"local" deploy to file share uses current timestamp

### ISSUE THREAD

**Issue by zmikes** [mkloubert/vscode-deploy-reloaded#84]
### Description

When deploying code to a file share, the files are written with the current timestamp. So files appear newer than the source files.

### Actual behavior

Copied files are timestamped "now". 
Result is that future deployments with  `"checkBeforeDeploy": true` report that the destination files are newer!

### Expected behavior

Copied files are transferred with their own existing creation date as the creation date at the destination

### Steps to reproduce

Deploy an existing file to the file share and compare the timestamps

#### Example config

```
        "targets": [
       

            {
                "type": "local",
                "name": "test server share",
                "description": "A SMB shared network folder",

                "dir": "\\\\server\\Websites\\application",
               
                // "checkBeforeDeploy": true
            },
```
#### Screenshot

![image](https://user-images.githubusercontent.com/15371324/42330270-b2dbadd0-806a-11e8-9d35-11359045b181.png)

### Your environment

- Operating system: Windows 10 -> Windows Server 2012
- Visual Studio Code version: 1.23.1
- Extension version: 0.75.1    (just uninstalled and reinstalled but still 0.75.1 not the published 0.82!)

### Additional comments

I am migrating from Visual Studio 2013 with WebDeploy -  a migration guide would be useful.

Thanks for you extension - much appreciated.

**Comment by mkloubert** [comment]
@zmikes 

**Since version 0.83.0**, the timestamps are trying to be synced after [local files](https://github.com/mkloubert/vscode-deploy-reloaded/wiki/target_local) have been downloaded or uploaded by default.

You can deactivate the feature by setting new `syncTime` to `(false)`:

```json
{
    "deploy.reloaded": {
        "targets": [
            {
                "type": "local",
                "name": "test server share",
                "description": "A SMB shared network folder",
                
                "syncTime": false
            }
        ]
    }
}
```
