### ISSUE TITLE
Help needed with mappings

### ISSUE THREAD

**Issue by DavidA2014** [mkloubert/vscode-deploy-reloaded#86]
- Operating system: Windows 10
- Visual Studio Code version: 1.24.1
- Extension version: 0.82.0

I don't understand how to specify mappings.  I want to deploy a single file locally (on Windows) from:

    <workspace_root>\Software\Tools\Wireshark\xran.lua

to:

    c:\MyDir\xran.lua

My packages object specifies:

    "files": [  "Software/Tools/Wireshark/xran.lua" ],

What should the mappings object contain please?

**Comment by mkloubert** [comment]
@DavidA2014 

```json
{
    "deploy": {
        "targets": [
            {
                "type": "local",

                "dir": "c:/MyDir/xran.lua",   

                "mappings": {
                    "/Software/Tools/Wireshark/**/*": "/"
                }
            }
        ]
    }
}
```

All files inside `<workspace_root>\Software\Tools\Wireshark` (`/Software/Tools/Wireshark/**/*`) will be mapped to `c:\MyDir` (`/`).

More information can be found in the [wiki](https://github.com/mkloubert/vscode-deploy-reloaded/wiki/folder_mappings).

**Comment by DavidA2014** [comment]
Thank you, that works fine now.

Just a suggestion: could you expand the folder_mappings section in the wiki to explain the syntax a bit more?  Perhaps it could give more examples and explain the meaning of '**'?

Thanks for a great plugin.
